print("Problem 4 in Exercises 6.8")
print("Show that removing the x_male term from equation (6.18) implies the model for females and the model for males have the same intercept, but different slopes")
print("Solution:")
print("The model with all terms is as follows: (6.18)")
print("     y = B_0  + B_1 * x_ssf + B_2 * x_male + B_3 * x_interaction")
print("By removing the x_male term we get:")
print("y = B_0  + B_1 * x_ssf + B_3 * x_interaction")
print("This can be expanded to:")
print("     y = B_0  + B_1 * x_ssf + B_3 * x_ssf * x_male")
print("By combining the x_ssf terms we get:")
print("     y = B_0  + (B_1 + B_3*x_male) * x_ssf")
print("For the male model this reduces to: ")
print("     y = B_0  + (B_1 + B_3) * x_ssf")
print("And the female model this reduces to: ")
print("     y = B_0  + B_1 * x_ssf")
print("Because both models have the same intercept (B_0), but different slopes (B_1 + B3 and B_1 respectively), we have shown the statement of the problem is true.")